create table TRANSACTION (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	ORIGIN_ID INTEGER, 
	DESTINY_ID INTEGER,
	MOMENT DATETIME,
	DESCRIPTION VARCHAR(500),
	TRANSACTION_VALUE FLOAT DEFAULT 0,

	foreign key(ORIGIN_ID) references ACCOUNT(ID),
	foreign key(DESTINY_ID) references ACCOUNT(ID)
);
